version: '3'

services:
    db:
        image: postgres
    web:
        build: 
            context: .
            dockerfile: Dockerfile
            args:
                http_proxy: $http_proxy
                https_proxy: $https_proxy 
        command: >
            bash -c "python manage.py runserver 0.0.0.0:8000
            && python manage.py sqlmigrate blog 0001"
        volumes:
        - .:/code
        ports:
        - "8000:8000"
        depends_on:
        - db
                                                                                        
